theme: jekyll-theme-architect
title: "geekinside.me"
name: "geekinside.me"
description: >- # this means to ignore newlines until "baseurl:"
  geekinside.me
google_analytics: UA-140788349-1
markdown: kramdown
lang: ja_JP
tagline:
author :
  name : geekinside.me
  email: admin@geekinside.me
  twitter: geekinsideme1
  github: geekinsideme
  feedburner : feedname
