theme: jekyll-theme-architect
title: geekinside.me
email: admin@geekinside.me
description: >- # this means to ignore newlines until "baseurl:"
  geekinside.me
twitter_username: geekinsideme1
github_username: geekinsideme
